[package]
name = "CodeRaidBot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.20.0", default-features = false, features = [
    "rt",
    "rt-multi-thread",
    "macros",
] }
poise = "0.2.1"
